version: "3.9"

services:
  api:
    build: .
    environment:
      MAX_TOKENS: 8192
      MAX_MODEL_LEN: 16384
      GPU_MEMORY_UTILIZATION: 0.7
      TEMPERATURE: 0.0
      GENERATOR_MODEL: Qwen/Qwen3.5-2B
    #container_name: lecture-rag-api
    ports:
      - "8000:8000"
    volumes:
      - rag_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  rag_data: